### PR TITLE
Side bar fix

### PR DESCRIPTION
**Pull request by SlowKingV**
New fixes for the side bar.

### CODE REVIEW

**Review by imhta — APPROVED** [review]
# Changes Required 🛑 

### Hello @SlowKingV @Joecleverman 👋, You have done a good job. But before you merge the project. fix below issues

- Just write a good readme. [for example check this](https://github.com/imhta/Youtube-Videoplayer-Template)
- Fix css validation issue [validator link](https://jigsaw.w3.org/css-validator/validator)
image

> NOTE: You don't want to create new pull request for every review. Just maintain a single pull request.

----
### Don't forgot to request for another code review
----

**Happy coding**
Pon Muthu Selvam N
_If you have any queries, feel free to ping me on slack_

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑

**Comment by SlowKingV** [comment]
We fixed it.

**Review by imhta — APPROVED** [review]
# Project Approved 👍 

Hello @SlowKingV @Joecleverman , 👋 You have done a good job in this project.

- Kindly Just a readme to the project before you merge (with description, tech used, author like that)

----
#### Don't forgot to sumbit the project completion form

**Happy Coding**

Pon Muthu Selvam N
_If you have any queries, feel free to ping me in slack_

**Pull request merged**
